import { useState, useEffect, useRef, useMemo } from 'react'
import {
  Button, Space, Card, Select, Tag, message, Empty, Spin,
  Modal, Form, Input, Alert, Dropdown, Typography
} from 'antd'
import {
  DeleteOutlined, SettingOutlined, BulbOutlined,
  ReloadOutlined, MagicOutlined, ArrowLeftOutlined
} from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import ReactECharts from 'echarts-for-react'
import { buildChartOption } from '@/pages/dashboard-designer/utils/chartOptions'
import { getDatasetAll, getDatasetPreview } from '@/api/dataset'
import { autoGenerateDashboard, recommendChartType } from '@/api/ai'
import type { DataSet, AutoDashboardCard, FieldInfo, ChartType } from '@/types'
import {
  analyzeFields,
  getFieldCategoryColor,
  getFieldCategoryLabel,
  getChartTypeLabel,
  getChartTypeIcon,
  recommendChartType as localRecommend
} from './utils/chartRecommender'
import './style.css'

const { Title, Text } = Typography

const ZeroCodeDashboardBuilder = () => {
  const navigate = useNavigate()
  const [datasets, setDatasets] = useState<DataSet[]>([])
  const [selectedDataset, setSelectedDataset] = useState<number | null>(null)
  const [datasetFields, setDatasetFields] = useState<FieldInfo[]>([])
  const [previewData, setPreviewData] = useState<Record<string, any>[]>([])
  const [cards, setCards] = useState<AutoDashboardCard[]>([])
  const [selectedCardId, setSelectedCardId] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [canvasRef] = useState(() => document.createElement('div'))

  const [draggingField, setDraggingField] = useState<FieldInfo | null>(null)
  const [hoveredCardId, setHoveredCardId] = useState<string | null>(null)
  const [chartConfigVisible, setChartConfigVisible] = useState(false)
  const [configForm] = Form.useForm()

  useEffect(() => {
    getDatasetAll().then(setDatasets).catch(() => {})
  }, [])

  useEffect(() => {
    if (!selectedDataset) {
      setDatasetFields([])
      setPreviewData([])
      return
    }
    loadDatasetData(selectedDataset)
  }, [selectedDataset])

  const loadDatasetData = async (datasetId: number) => {
    setLoading(true)
    try {
      const res = await getDatasetPreview(datasetId, {}, 100)
      if (res.success !== false && res.rows) {
        setPreviewData(res.rows)
        const fields = analyzeFields(res.rows)
        setDatasetFields(fields)
      } else {
        setPreviewData([])
        setDatasetFields([])
      }
    } catch {
      setPreviewData([])
      setDatasetFields([])
    } finally {
      setLoading(false)
    }
  }

  const dimensions = useMemo(
    () => datasetFields.filter(f => f.category === 'DIMENSION' || f.category === 'GEO'),
    [datasetFields]
  )
  const measures = useMemo(
    () => datasetFields.filter(f => f.category === 'MEASURE'),
    [datasetFields]
  )
  const dates = useMemo(
    () => datasetFields.filter(f => f.category === 'DATE'),
    [datasetFields]
  )

  const handleAutoGenerate = async () => {
    if (!selectedDataset) {
      message.warning('请先选择数据集')
      return
    }
    setAutoGenerating(true)
    try {
      const res = await autoGenerateDashboard(selectedDataset)
      setCards(res.cards || [])
      message.success(`已自动生成 ${res.cards?.length || 0} 个图表卡片`)
    } catch {
      message.error('自动生成失败，请稍后重试')
    } finally {
      setAutoGenerating(false)
    }
  }

  const handleFieldDragStart = (field: FieldInfo) => {
    setDraggingField(field)
  }

  const handleFieldDragEnd = () => {
    setDraggingField(null)
    setHoveredCardId(null)
  }

  const handleCanvasDrop = async (e: React.DragEvent) => {
    e.preventDefault()
    if (!draggingField || !selectedDataset) return

    const fieldsForRecommend = [draggingField]
    try {
      const rec = await recommendChartType(selectedDataset, [draggingField.name])
      const newCard: AutoDashboardCard = {
        id: Date.now().toString(),
        datasetId: selectedDataset,
        chartType: rec.recommendedType as ChartType,
        title: rec.reason.replace(/^单(维度|度量)字段\s+'([^']+)'\s*，/, '').replace('建议', '').split('展示')[0],
        xField: rec.xFieldCandidates[0],
        yFields: rec.yFieldCandidates,
        width: rec.suggestedCardWidth,
        height: rec.suggestedCardHeight,
        reason: rec.reason,
        alternatives: rec.alternatives
      }
      setCards(prev => [...prev, newCard])
      message.success(`已生成 ${getChartTypeLabel(rec.recommendedType as ChartType)} 卡片`)
    } catch {
      const localRec = localRecommend(fieldsForRecommend)
      const newCard: AutoDashboardCard = {
        id: Date.now().toString(),
        datasetId: selectedDataset,
        chartType: localRec.recommendedType as ChartType,
        title: localRec.reason,
        xField: localRec.xFieldCandidates[0],
        yFields: localRec.yFieldCandidates,
        width: localRec.suggestedCardWidth,
        height: localRec.suggestedCardHeight,
        reason: localRec.reason,
        alternatives: localRec.alternatives
      }
      setCards(prev => [...prev, newCard])
      message.success(`已生成卡片`)
    } finally {
      setDraggingField(null)
    }
  }

  const handleCardDrop = async (cardId: string, e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    if (!draggingField || !selectedDataset) return

    const card = cards.find(c => c.id === cardId)
    if (!card) return

    const existingFields = new Set([
      card.xField,
      ...(card.yFields || [])
    ].filter(Boolean))

    if (existingFields.has(draggingField.name)) {
      message.warning('该字段已在此卡片中')
      return
    }

    const allFields = [...existingFields, draggingField.name]
    try {
      const rec = await recommendChartType(selectedDataset, Array.from(allFields))
      setCards(prev => prev.map(c =>
        c.id === cardId ? {
          ...c,
          chartType: rec.recommendedType as ChartType,
          xField: rec.xFieldCandidates[0] || c.xField,
          yFields: rec.yFieldCandidates.length > 0 ? rec.yFieldCandidates : c.yFields,
          width: rec.suggestedCardWidth,
          height: rec.suggestedCardHeight,
          reason: rec.reason,
          alternatives: rec.alternatives
        } : c
      ))
      message.success(`已更新为 ${getChartTypeLabel(rec.recommendedType as ChartType)}`)
    } catch {
      message.warning('添加字段成功，建议手动调整图表类型')
      const isMeasure = draggingField.category === 'MEASURE'
      setCards(prev => prev.map(c =>
        c.id === cardId ? {
          ...c,
          yFields: isMeasure ? [...(c.yFields || []), draggingField.name] : c.yFields,
          xField: !isMeasure ? draggingField.name : c.xField
        } : c
      ))
    } finally {
      setDraggingField(null)
      setHoveredCardId(null)
    }
  }

  const handleDeleteCard = (cardId: string) => {
    setCards(prev => prev.filter(c => c.id !== cardId))
    if (selectedCardId === cardId) setSelectedCardId(null)
  }

  const handleChangeChartType = (cardId: string, newType: ChartType) => {
    setCards(prev => prev.map(c =>
      c.id === cardId ? { ...c, chartType: newType } : c
    ))
  }

  const handleConfigCard = (card: AutoDashboardCard) => {
    setSelectedCardId(card.id)
    configForm.setFieldsValue({
      title: card.title,
      xField: card.xField,
      yFields: card.yFields
    })
    setChartConfigVisible(true)
  }

  const handleConfigSave = async () => {
    try {
      const values = await configForm.validateFields()
      setCards(prev => prev.map(c =>
        c.id === selectedCardId ? { ...c, ...values } : c
      ))
      setChartConfigVisible(false)
      message.success('配置已更新')
    } catch {}
  }

  const selectedCard = useMemo(
    () => cards.find(c => c.id === selectedCardId),
    [cards, selectedCardId]
  )

  return (
    <div className="zero-code-dashboard">
      <div className="zcd-header">
        <Button icon={<ArrowLeftOutlined />} type="text" onClick={() => navigate(-1)}>返回</Button>
        <Title level={4} style={{ margin: 0, color: '#fff' }}>零代码仪表板</Title>
        <div style={{ flex: 1 }} />
        <Space>
          <Select
            style={{ width: 280 }}
            placeholder="请选择数据集"
            value={selectedDataset}
            onChange={setSelectedDataset}
            showSearch
            optionFilterProp="label"
          >
            {datasets.map(ds => (
              <Select.Option key={ds.id} value={ds.id} label={ds.name}>
                {ds.name}
              </Select.Option>
            ))}
          </Select>
          <Button icon={<ReloadOutlined />} onClick={() => selectedDataset && loadDatasetData(selectedDataset)} disabled={!selectedDataset}>
            刷新数据
          </Button>
          <Button
            type="primary"
            icon={<MagicOutlined />}
            onClick={handleAutoGenerate}
            loading={autoGenerating}
            disabled={!selectedDataset}
          >
            一键自动生成
          </Button>
        </Space>
      </div>

      <div className="zcd-body">
        <div className="zcd-sidebar">
          {selectedDataset ? (
            loading ? (
              <div style={{ padding: 40, textAlign: 'center' }}>
                <Spin tip="加载字段中..." />
              </div>
            ) : (
              <div>
                <Alert
                  message="拖拽字段到右侧画布自动生成图表"
                  description="系统将根据字段类型智能推荐最佳图表类型。拖到已有卡片可添加字段。"
                  type="info"
                  showIcon
                  style={{ marginBottom: 16 }}
                />

                {dates.length > 0 && (
                  <FieldGroup
                    title="日期字段"
                    fields={dates}
                    onDragStart={handleFieldDragStart}
                    onDragEnd={handleFieldDragEnd}
                  />
                )}
                {dimensions.length > 0 && (
                  <FieldGroup
                    title="维度字段"
                    fields={dimensions}
                    onDragStart={handleFieldDragStart}
                    onDragEnd={handleFieldDragEnd}
                  />
                )}
                {measures.length > 0 && (
                  <FieldGroup
                    title="度量字段"
                    fields={measures}
                    onDragStart={handleFieldDragStart}
                    onDragEnd={handleFieldDragEnd}
                  />
                )}

                {datasetFields.filter(f => f.category === 'UNKNOWN').length > 0 && (
                  <FieldGroup
                    title="其他字段"
                    fields={datasetFields.filter(f => f.category === 'UNKNOWN')}
                    onDragStart={handleFieldDragStart}
                    onDragEnd={handleFieldDragEnd}
                  />
                )}

                <div style={{ marginTop: 16, padding: '12px 16px', background: 'rgba(255,255,255,0.05)', borderRadius: 6 }}>
                  <Text style={{ color: '#aaa', fontSize: 12 }}>
                    数据预览：{previewData.length} 行
                  </Text>
                </div>
              </div>
            )
          ) : (
            <Empty description="请先选择数据集" />
          )}
        </div>

        <div
          className="zcd-canvas"
          ref={canvasRef as any}
          onDragOver={(e) => { e.preventDefault(); e.dataTransfer.dropEffect = 'copy' }}
          onDrop={handleCanvasDrop}
        >
          {cards.length === 0 ? (
            <div className="zcd-empty-canvas">
              {draggingField ? (
                <div className="zcd-drop-hint">
                  <BulbOutlined style={{ fontSize: 48, color: '#1890ff', marginBottom: 12 }} />
                  <div style={{ fontSize: 16, color: '#1890ff' }}>松开鼠标，自动生成图表</div>
                  <div style={{ fontSize: 13, color: '#666', marginTop: 8 }}>
                    系统将智能推荐最佳图表类型
                  </div>
                </div>
              ) : (
                <Empty
                  description={
                    <div style={{ textAlign: 'center' }}>
                      <div style={{ fontSize: 15, color: '#666', marginBottom: 8 }}>
                        从左侧拖拽字段到此处，或点击「一键自动生成」
                      </div>
                      <div style={{ fontSize: 12, color: '#999' }}>
                        无需模板设计，系统智能推荐图表
                      </div>
                    </div>
                  }
                />
              )}
            </div>
          ) : (
            <div className="zcd-cards-container">
              {cards.map(card => (
                <DashboardCard
                  key={card.id}
                  card={card}
                  data={previewData}
                  isSelected={selectedCardId === card.id}
                  isHovered={hoveredCardId === card.id}
                  isDragging={draggingField !== null}
                  onSelect={() => setSelectedCardId(card.id)}
                  onDelete={() => handleDeleteCard(card.id)}
                  onConfig={() => handleConfigCard(card)}
                  onChartTypeChange={(type) => handleChangeChartType(card.id, type)}
                  onDragOver={() => setHoveredCardId(card.id)}
                  onDragLeave={() => setHoveredCardId(null)}
                  onDrop={(e) => handleCardDrop(card.id, e)}
                />
              ))}
            </div>
          )}
        </div>

        <div className="zcd-right-panel">
          {selectedCard ? (
            <div className="zcd-card-config">
              <div className="zcd-config-title">卡片配置</div>
              <div className="zcd-config-item">
                <label>标题</label>
                <Input
                  value={selectedCard.title}
                  onChange={e => setCards(prev => prev.map(c =>
                    c.id === selectedCard.id ? { ...c, title: e.target.value } : c
                  ))}
                />
              </div>
              <div className="zcd-config-item">
                <label>图表类型</label>
                <Select
                  value={selectedCard.chartType}
                  onChange={(v: ChartType) => handleChangeChartType(selectedCard.id, v)}
                >
                  {['bar', 'line', 'pie', 'radar', 'scatter'].map(type => (
                    <Select.Option key={type} value={type}>
                      {getChartTypeIcon(type as ChartType)} {getChartTypeLabel(type as ChartType)}
                    </Select.Option>
                  ))}
                </Select>
              </div>
              <div className="zcd-config-item">
                <label>X轴字段</label>
                <Select
                  value={selectedCard.xField}
                  onChange={v => setCards(prev => prev.map(c =>
                    c.id === selectedCard.id ? { ...c, xField: v } : c
                  ))}
                >
                  {datasetFields.map(f => (
                    <Select.Option key={f.name} value={f.name}>{f.name}</Select.Option>
                  ))}
                </Select>
              </div>
              <div className="zcd-config-item">
                <label>Y轴字段</label>
                <Select
                  mode="tags"
                  value={selectedCard.yFields}
                  onChange={v => setCards(prev => prev.map(c =>
                    c.id === selectedCard.id ? { ...c, yFields: v } : c
                  ))}
                >
                  {datasetFields.filter(f => f.category === 'MEASURE').map(f => (
                    <Select.Option key={f.name} value={f.name}>{f.name}</Select.Option>
                  ))}
                </Select>
              </div>
              <div className="zcd-config-item">
                <label>推荐理由</label>
                <div className="zcd-reason">
                  {selectedCard.reason || '手动配置'}
                </div>
              </div>
              {selectedCard.alternatives && selectedCard.alternatives.length > 1 && (
                <div className="zcd-config-item">
                  <label>备选类型</label>
                  <Space wrap size={4}>
                    {selectedCard.alternatives.filter(a => a !== selectedCard.chartType).map(type => (
                      <Tag
                        key={type}
                        color="blue"
                        style={{ cursor: 'pointer', margin: 2 }}
                        onClick={() => handleChangeChartType(selectedCard.id, type as ChartType)}
                      >
                        {getChartTypeIcon(type as ChartType)} {getChartTypeLabel(type as ChartType)}
                      </Tag>
                    ))}
                  </Space>
                </div>
              )}
              <div className="zcd-config-actions">
                <Button block danger icon={<DeleteOutlined />} onClick={() => handleDeleteCard(selectedCard.id)}>
                  删除卡片
                </Button>
              </div>
            </div>
          ) : (
            <div className="zcd-right-empty">
              <Empty description="选择卡片查看配置" />
            </div>
          )}
        </div>
      </div>

      <Modal
        title="图表配置"
        open={chartConfigVisible}
        onOk={handleConfigSave}
        onCancel={() => setChartConfigVisible(false)}
        width={520}
      >
        <Form form={configForm} layout="vertical">
          <Form.Item label="标题" name="title">
            <Input placeholder="请输入标题" />
          </Form.Item>
          <Form.Item label="X轴字段" name="xField">
            <Select>
              {datasetFields.map(f => (
                <Select.Option key={f.name} value={f.name}>{f.name}</Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item label="Y轴字段" name="yFields">
            <Select mode="tags">
              {datasetFields.filter(f => f.category === 'MEASURE').map(f => (
                <Select.Option key={f.name} value={f.name}>{f.name}</Select.Option>
              ))}
            </Select>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

const FieldGroup: React.FC<{
  title: string
  fields: FieldInfo[]
  onDragStart: (field: FieldInfo) => void
  onDragEnd: () => void
}> = ({ title, fields, onDragStart, onDragEnd }) => {
  if (!fields || fields.length === 0) return null
  const category = fields[0].category
  const color = getFieldCategoryColor(category)

  return (
    <div className="zcd-field-group">
      <div className="zcd-field-group-title">
        <span className="zcd-field-dot" style={{ background: color }} />
        <span>{title}</span>
        <Tag color={color} style={{ marginLeft: 6 }}>{fields.length}</Tag>
      </div>
      <div className="zcd-field-list">
        {fields.map(field => (
          <div
            key={field.name}
            className="zcd-field-item"
            draggable
            onDragStart={() => onDragStart(field)}
            onDragEnd={onDragEnd}
            title={`${field.name} (${getFieldCategoryLabel(field.category)}, ${field.type}, ${field.distinctCount}个不同值)`}
          >
            <span className="zcd-field-dot" style={{ background: getFieldCategoryColor(field.category) }} />
            <span className="zcd-field-name">{field.name}</span>
            <span className="zcd-field-meta">{field.distinctCount}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

const DashboardCard: React.FC<{
  card: AutoDashboardCard
  data: Record<string, any>[]
  isSelected: boolean
  isHovered: boolean
  isDragging: boolean
  onSelect: () => void
  onDelete: () => void
  onConfig: () => void
  onChartTypeChange: (type: ChartType) => void
  onDragOver: () => void
  onDragLeave: () => void
  onDrop: (e: React.DragEvent) => void
}> = ({ card, data, isSelected, isHovered, isDragging, onSelect, onDelete, onConfig, onChartTypeChange, onDragOver, onDragLeave, onDrop }) => {
  const chartOption = useMemo(() =>
    buildChartOption(card.chartType, card.title, data, card.xField, card.yFields),
    [card.chartType, card.title, data, card.xField, card.yFields]
  )

  const chartTypeMenu = {
    items: ['bar', 'line', 'pie', 'radar', 'scatter'].map(type => ({
      key: type,
      label: (
        <span>
          {getChartTypeIcon(type as ChartType)} {getChartTypeLabel(type as ChartType)}
        </span>
      ),
      icon: type === card.chartType ? <span style={{ color: '#1890ff' }}>✓</span> : undefined
    })),
    onClick: ({ key }: any) => onChartTypeChange(key)
  }

  return (
    <Card
      className={`zcd-dashboard-card ${isSelected ? 'zcd-card-selected' : ''} ${isHovered ? 'zcd-card-hover' : ''}`}
      onDragOver={(e) => { e.preventDefault(); onDragOver() }}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      onClick={(e) => { e.stopPropagation(); onSelect() }}
      styles={{ body: { padding: 0 } }}
      title={
        <div className="zcd-card-header" onClick={e => e.stopPropagation()}>
          <span className="zcd-card-icon">
            {getChartTypeIcon(card.chartType)}
          </span>
          <span className="zcd-card-title">{card.title}</span>
          <Space className="zcd-card-actions">
            <Dropdown menu={chartTypeMenu} placement="bottomRight">
              <Button size="small" type="text">
                {getChartTypeLabel(card.chartType)}
              </Button>
            </Dropdown>
            <Button size="small" type="text" icon={<SettingOutlined />} onClick={onConfig} />
            <Button size="small" type="text" danger icon={<DeleteOutlined />} onClick={onDelete} />
          </Space>
        </div>
      }
      style={{
        width: Math.min(card.width, 520),
        height: card.height + 48
      }}
    >
      {isHovered && isDragging && (
        <div className="zcd-card-drop-overlay">
          <MagicOutlined style={{ fontSize: 32, color: '#1890ff' }} />
          <div style={{ marginTop: 8, color: '#1890ff' }}>添加字段到此卡片</div>
        </div>
      )}
      <div className="zcd-chart-container" style={{ height: card.height }}>
        {data.length > 0 ? (
          <ReactECharts
            option={chartOption}
            style={{ width: '100%', height: '100%' }}
            notMerge
            lazyUpdate
          />
        ) : (
          <div className="zcd-chart-empty">无数据</div>
        )}
      </div>
    </Card>
  )
}

export default ZeroCodeDashboardBuilder
