package com.openreport.admin.controller;

import com.openreport.admin.entity.DataSet;
import com.openreport.admin.service.DataSetService;
import com.openreport.common.result.Result;
import com.openreport.engine.ai.ChartTypeRecommender;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@Slf4j
@Api(tags = "智能图表推荐")
@RestController
@RequestMapping("/ai/chart")
public class AiChartRecommendController {

    @Autowired
    private ChartTypeRecommender chartTypeRecommender;

    @Autowired
    private DataSetService dataSetService;

    @ApiOperation("根据字段推荐最佳图表类型")
    @PostMapping("/recommend/{datasetId}")
    public Result<Map<String, Object>> recommend(
            @PathVariable Long datasetId,
            @RequestBody Map<String, Object> body) {
        try {
            DataSet dataSet = dataSetService.getById(datasetId);
            if (dataSet == null) {
                return Result.error("数据集不存在");
            }

            @SuppressWarnings("unchecked")
            List<String> selectedFields = (List<String>) body.get("fields");
            if (selectedFields == null || selectedFields.isEmpty()) {
                return Result.error("请选择字段");
            }

            Map<String, Object> params = (Map<String, Object>) body.get("params");
            Integer limit = body.get("limit") != null ? Integer.valueOf(body.get("limit").toString()) : 50;

            Map<String, Object> previewResult = dataSetService.previewData(datasetId, params != null ? params : new HashMap<>(), limit);
            if (previewResult == null || Boolean.FALSE.equals(previewResult.get("success"))) {
                return Result.error("获取数据失败");
            }

            @SuppressWarnings("unchecked")
            List<Map<String, Object>> rows = (List<Map<String, Object>>) previewResult.get("rows");
            if (rows == null || rows.isEmpty()) {
                return Result.error("数据为空，无法推荐");
            }

            List<Map<String, String>> columnMeta = new ArrayList<>();
            for (String fieldName : selectedFields) {
                for (Map<String, Object> row : rows) {
                    if (row.containsKey(fieldName)) {
                        Map<String, String> col = new HashMap<>();
                        col.put("name", fieldName);
                        Object val = row.get(fieldName);
                        String type = inferType(val);
                        col.put("type", type);
                        columnMeta.add(col);
                        break;
                    }
                }
            }

            List<ChartTypeRecommender.FieldInfo> fieldInfos = chartTypeRecommender.analyzeFields(rows, columnMeta);
            ChartTypeRecommender.RecommendationResult recommendation = chartTypeRecommender.recommend(fieldInfos);

            Map<String, Object> result = new HashMap<>();
            result.put("recommendedType", recommendation.getRecommendedType().name().toLowerCase());
            result.put("reason", recommendation.getReason());
            result.put("alternatives", recommendation.getAlternatives().stream()
                    .map(t -> t.name().toLowerCase()).toList());
            result.put("xFieldCandidates", recommendation.getXFieldCandidates());
            result.put("yFieldCandidates", recommendation.getYFieldCandidates());
            result.put("suggestedCardWidth", recommendation.getSuggestedCardWidth());
            result.put("suggestedCardHeight", recommendation.getSuggestedCardHeight());

            List<Map<String, Object>> fieldsInfo = new ArrayList<>();
            for (ChartTypeRecommender.FieldInfo fi : fieldInfos) {
                Map<String, Object> fm = new HashMap<>();
                fm.put("name", fi.getName());
                fm.put("type", fi.getType());
                fm.put("category", fi.getCategory().name());
                fm.put("distinctCount", fi.getDistinctCount());
                fm.put("sampleValue", fi.getSampleValue());
                fieldsInfo.add(fm);
            }
            result.put("fields", fieldsInfo);

            return Result.success(result);
        } catch (Exception e) {
            log.error("推荐图表类型失败", e);
            return Result.error("推荐失败: " + e.getMessage());
        }
    }

    @ApiOperation("智能分析数据集 - 自动生成仪表板卡片")
    @PostMapping("/auto-dashboard/{datasetId}")
    public Result<Map<String, Object>> autoGenerateDashboard(
            @PathVariable Long datasetId,
            @RequestBody(required = false) Map<String, Object> params) {
        try {
            DataSet dataSet = dataSetService.getById(datasetId);
            if (dataSet == null) {
                return Result.error("数据集不存在");
            }

            Map<String, Object> queryParams = params != null ? params : new HashMap<>();
            Integer limit = 100;

            Map<String, Object> previewResult = dataSetService.previewData(datasetId, queryParams, limit);
            if (previewResult == null || Boolean.FALSE.equals(previewResult.get("success"))) {
                return Result.error("获取数据失败");
            }

            @SuppressWarnings("unchecked")
            List<Map<String, Object>> rows = (List<Map<String, Object>>) previewResult.get("rows");
            if (rows == null || rows.isEmpty()) {
                return Result.error("数据为空，无法生成");
            }

            Map<String, Object> firstRow = rows.get(0);
            List<Map<String, String>> columnMeta = new ArrayList<>();
            for (String colName : firstRow.keySet()) {
                Map<String, String> col = new HashMap<>();
                col.put("name", colName);
                col.put("type", inferType(firstRow.get(colName)));
                columnMeta.add(col);
            }

            List<ChartTypeRecommender.FieldInfo> fieldInfos = chartTypeRecommender.analyzeFields(rows, columnMeta);

            List<ChartTypeRecommender.FieldInfo> dimensions = fieldInfos.stream()
                    .filter(f -> f.getCategory() == ChartTypeRecommender.FieldCategory.DIMENSION
                            || f.getCategory() == ChartTypeRecommender.FieldCategory.DATE
                            || f.getCategory() == ChartTypeRecommender.FieldCategory.GEO)
                    .toList();
            List<ChartTypeRecommender.FieldInfo> measures = fieldInfos.stream()
                    .filter(f -> f.getCategory() == ChartTypeRecommender.FieldCategory.MEASURE)
                    .toList();

            List<Map<String, Object>> cards = new ArrayList<>();

            if (measures.isEmpty() && dimensions.isEmpty()) {
                Map<String, Object> card = buildDefaultTableCard(datasetId, fieldInfos);
                cards.add(card);
            } else {
                for (ChartTypeRecommender.FieldInfo measure : measures) {
                    if (!dimensions.isEmpty()) {
                        ChartTypeRecommender.FieldInfo bestDim = selectBestDimension(dimensions, measure);
                        List<ChartTypeRecommender.FieldInfo> fieldsForRecommend = new ArrayList<>();
                        fieldsForRecommend.add(bestDim);
                        fieldsForRecommend.add(measure);

                        ChartTypeRecommender.RecommendationResult rec = chartTypeRecommender.recommend(fieldsForRecommend);

                        Map<String, Object> card = new HashMap<>();
                        card.put("id", UUID.randomUUID().toString().replace("-", ""));
                        card.put("datasetId", datasetId);
                        card.put("chartType", rec.getRecommendedType().name().toLowerCase());
                        card.put("title", buildCardTitle(rec.getRecommendedType(), bestDim, measure));
                        card.put("xField", bestDim.getName());
                        card.put("yFields", new String[]{measure.getName()});
                        card.put("width", rec.getSuggestedCardWidth());
                        card.put("height", rec.getSuggestedCardHeight());
                        card.put("reason", rec.getReason());
                        card.put("alternatives", rec.getAlternatives().stream()
                                .map(t -> t.name().toLowerCase()).toList());
                        cards.add(card);
                    } else {
                        List<ChartTypeRecommender.FieldInfo> fieldsForRecommend = new ArrayList<>();
                        fieldsForRecommend.add(measure);
                        ChartTypeRecommender.RecommendationResult rec = chartTypeRecommender.recommend(fieldsForRecommend);

                        Map<String, Object> card = new HashMap<>();
                        card.put("id", UUID.randomUUID().toString().replace("-", ""));
                        card.put("datasetId", datasetId);
                        card.put("chartType", rec.getRecommendedType().name().toLowerCase());
                        card.put("title", buildKpiTitle(measure));
                        card.put("xField", null);
                        card.put("yFields", new String[]{measure.getName()});
                        card.put("width", rec.getSuggestedCardWidth());
                        card.put("height", rec.getSuggestedCardHeight());
                        card.put("reason", rec.getReason());
                        cards.add(card);
                    }
                }
            }

            Map<String, Object> result = new HashMap<>();
            result.put("cards", cards);
            result.put("datasetName", dataSet.getName());
            result.put("totalMeasures", measures.size());
            result.put("totalDimensions", dimensions.size());
            result.put("rows", rows);

            return Result.success(result);
        } catch (Exception e) {
            log.error("自动生成仪表板失败", e);
            return Result.error("生成失败: " + e.getMessage());
        }
    }

    private String inferType(Object val) {
        if (val == null) return "string";
        if (val instanceof Number) {
            if (val instanceof Integer || val instanceof Long) return "bigint";
            if (val instanceof Double || val instanceof Float) return "decimal";
            return "number";
        }
        if (val instanceof java.util.Date || val instanceof java.time.temporal.Temporal) {
            return "datetime";
        }
        if (val instanceof Boolean) return "bool";
        return "string";
    }

    private Map<String, Object> buildDefaultTableCard(Long datasetId, List<ChartTypeRecommender.FieldInfo> fields) {
        Map<String, Object> card = new HashMap<>();
        card.put("id", UUID.randomUUID().toString().replace("-", ""));
        card.put("datasetId", datasetId);
        card.put("chartType", "table");
        card.put("title", "数据明细表");
        card.put("xField", fields.isEmpty() ? null : fields.get(0).getName());
        card.put("yFields", fields.stream().map(ChartTypeRecommender.FieldInfo::getName).toArray());
        card.put("width", 900);
        card.put("height", 450);
        card.put("reason", "未识别到有效维度或度量，默认展示表格");
        return card;
    }

    private ChartTypeRecommender.FieldInfo selectBestDimension(List<ChartTypeRecommender.FieldInfo> dimensions,
                                                                ChartTypeRecommender.FieldInfo measure) {
        for (ChartTypeRecommender.FieldInfo dim : dimensions) {
            if (dim.getCategory() == ChartTypeRecommender.FieldCategory.DATE) {
                return dim;
            }
        }
        ChartTypeRecommender.FieldInfo best = dimensions.get(0);
        int bestScore = -1;
        for (ChartTypeRecommender.FieldInfo dim : dimensions) {
            int score = 0;
            if (dim.getDistinctCount() != null) {
                int dc = dim.getDistinctCount();
                if (dc >= 3 && dc <= 12) score += 10;
                else if (dc > 12 && dc <= 20) score += 5;
            }
            if (dim.getCategory() == ChartTypeRecommender.FieldCategory.GEO) score += 3;
            if (score > bestScore) {
                bestScore = score;
                best = dim;
            }
        }
        return best;
    }

    private String buildCardTitle(ChartTypeRecommender.ChartType type,
                                   ChartTypeRecommender.FieldInfo dim,
                                   ChartTypeRecommender.FieldInfo measure) {
        String dimName = dim.getName();
        String measureName = measure.getName();
        String typeLabel = switch (type) {
            case BAR -> "柱状图";
            case LINE -> "折线图";
            case PIE -> "饼图";
            case RADAR -> "雷达图";
            case SCATTER -> "散点图";
            case AREA -> "面积图";
            default -> "图表";
        };
        return String.format("%s 按 %s 分布 %s", measureName, dimName, typeLabel);
    }

    private String buildKpiTitle(ChartTypeRecommender.FieldInfo measure) {
        return "总" + measure.getName();
    }
}
