import { post } from '@/utils/request'
import { ChartRecommendationResult, AutoDashboardResult } from '@/types'

export const recommendChartType = (
  datasetId: number,
  fields: string[],
  params?: Record<string, any>,
  limit?: number
): Promise<ChartRecommendationResult> => {
  return post(`/ai/chart/recommend/${datasetId}`, { fields, params, limit })
}

export const autoGenerateDashboard = (
  datasetId: number,
  params?: Record<string, any>
): Promise<AutoDashboardResult> => {
  return post(`/ai/chart/auto-dashboard/${datasetId}`, params || {})
}
