CREATE TABLE IF NOT EXISTS `report_subscription` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL COMMENT '订阅名称',
  `report_id` bigint NOT NULL COMMENT '关联报表ID',
  `channels` varchar(500) NOT NULL COMMENT '推送渠道，逗号分隔：DINGTALK,WECOM,EMAIL',
  `frequency` varchar(20) NOT NULL DEFAULT 'DAILY' COMMENT '推送频率：DAILY/WEEKLY/MONTHLY',
  `push_time` time DEFAULT '09:00:00' COMMENT '推送时间（时:分）',
  `push_day_of_week` int DEFAULT 1 COMMENT '每周推送日（1-7，周一=1），frequency=WEEKLY时有效',
  `push_day_of_month` int DEFAULT 1 COMMENT '每月推送日（1-31），frequency=MONTHLY时有效',
  `dingtalk_webhook` varchar(500) DEFAULT NULL COMMENT '钉钉机器人Webhook地址',
  `dingtalk_secret` varchar(200) DEFAULT NULL COMMENT '钉钉机器人加签密钥',
  `wecom_webhook` varchar(500) DEFAULT NULL COMMENT '企业微信机器人Webhook地址',
  `email_list` varchar(1000) DEFAULT NULL COMMENT '邮件收件人，逗号分隔',
  `email_cc_list` varchar(1000) DEFAULT NULL COMMENT '邮件抄送人，逗号分隔',
  `email_subject` varchar(200) DEFAULT NULL COMMENT '邮件主题',
  `message_format` varchar(20) NOT NULL DEFAULT 'MARKDOWN' COMMENT '消息格式：MARKDOWN/CARD/TEXT',
  `content_template` text DEFAULT NULL COMMENT '自定义内容模板，支持变量：${reportName}/${date}/${dateTime}',
  `include_chart` tinyint(1) DEFAULT 0 COMMENT '是否包含图表摘要',
  `include_attachment` tinyint(1) DEFAULT 0 COMMENT '是否包含附件',
  `attachment_type` varchar(20) DEFAULT 'EXCEL' COMMENT '附件类型：EXCEL/PDF',
  `params` text DEFAULT NULL COMMENT '报表参数（JSON）',
  `retry_count` int DEFAULT 0 COMMENT '当前重试次数',
  `max_retry_count` int DEFAULT 3 COMMENT '最大重试次数',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：0-停用 1-启用',
  `last_push_time` datetime DEFAULT NULL COMMENT '上次推送时间',
  `next_push_time` datetime DEFAULT NULL COMMENT '下次推送时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` bigint DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_status` (`status`),
  KEY `idx_next_push_time` (`next_push_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='报表订阅';

CREATE TABLE IF NOT EXISTS `report_subscription_notify_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `subscription_id` bigint NOT NULL COMMENT '订阅ID',
  `report_id` bigint NOT NULL COMMENT '报表ID',
  `channel` varchar(20) NOT NULL COMMENT '推送渠道：DINGTALK/WECOM/EMAIL',
  `status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '推送状态：PENDING/SUCCESS/FAIL/RETRY',
  `retry_count` int DEFAULT 0 COMMENT '重试次数',
  `message_format` varchar(20) DEFAULT NULL COMMENT '消息格式',
  `request_data` text DEFAULT NULL COMMENT '请求数据',
  `response_data` text DEFAULT NULL COMMENT '响应数据',
  `error_msg` text DEFAULT NULL COMMENT '错误信息',
  `cost_time` bigint DEFAULT 0 COMMENT '耗时(ms)',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_subscription_id` (`subscription_id`),
  KEY `idx_channel` (`channel`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='报表订阅推送日志';
