-- =====================================================
-- Open Report 系统数据库建表脚本 (达梦 8)
-- 编码: UTF-8
-- 说明: 基于 MySQL 版本改写，适配达梦数据库语法
-- =====================================================

-- ----------------------------
-- 系统用户表
-- ----------------------------
DROP TABLE IF EXISTS "SYS_USER";
CREATE TABLE "SYS_USER" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "USERNAME" VARCHAR(64) NOT NULL,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "NICKNAME" VARCHAR(64),
  "EMAIL" VARCHAR(128),
  "PHONE" VARCHAR(32),
  "AVATAR" VARCHAR(255),
  "STATUS" SMALLINT NOT NULL DEFAULT 1,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UK_SYS_USER_USERNAME" UNIQUE ("USERNAME")
);
COMMENT ON TABLE "SYS_USER" IS '系统用户表';
COMMENT ON COLUMN "SYS_USER"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SYS_USER"."NICKNAME" IS '昵称';
COMMENT ON COLUMN "SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SYS_USER"."PHONE" IS '手机号';
COMMENT ON COLUMN "SYS_USER"."AVATAR" IS '头像';
COMMENT ON COLUMN "SYS_USER"."STATUS" IS '状态 0-禁用 1-启用';
COMMENT ON COLUMN "SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_USER"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_USER"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SYS_USER"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE OR REPLACE TRIGGER "TRG_SYS_USER_UPDATE_TIME"
BEFORE UPDATE ON "SYS_USER"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 系统角色表
-- ----------------------------
DROP TABLE IF EXISTS "SYS_ROLE";
CREATE TABLE "SYS_ROLE" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "ROLE_CODE" VARCHAR(64) NOT NULL,
  "ROLE_NAME" VARCHAR(64) NOT NULL,
  "DESCRIPTION" VARCHAR(255),
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UK_SYS_ROLE_CODE" UNIQUE ("ROLE_CODE")
);
COMMENT ON TABLE "SYS_ROLE" IS '系统角色表';
COMMENT ON COLUMN "SYS_ROLE"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_CODE" IS '角色编码';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "SYS_ROLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "SYS_ROLE"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE OR REPLACE TRIGGER "TRG_SYS_ROLE_UPDATE_TIME"
BEFORE UPDATE ON "SYS_ROLE"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 系统菜单表
-- ----------------------------
DROP TABLE IF EXISTS "SYS_MENU";
CREATE TABLE "SYS_MENU" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "PARENT_ID" BIGINT NOT NULL DEFAULT 0,
  "MENU_NAME" VARCHAR(64) NOT NULL,
  "MENU_TYPE" CHAR(1) NOT NULL,
  "PATH" VARCHAR(255),
  "COMPONENT" VARCHAR(255),
  "PERMS" VARCHAR(128),
  "ICON" VARCHAR(64),
  "SORT" INT NOT NULL DEFAULT 0,
  "VISIBLE" SMALLINT NOT NULL DEFAULT 1,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID")
);
COMMENT ON TABLE "SYS_MENU" IS '系统菜单表';
COMMENT ON COLUMN "SYS_MENU"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_MENU"."PARENT_ID" IS '父菜单ID';
COMMENT ON COLUMN "SYS_MENU"."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "SYS_MENU"."MENU_TYPE" IS '菜单类型 M-目录 C-菜单 F-按钮';
COMMENT ON COLUMN "SYS_MENU"."PATH" IS '路由路径';
COMMENT ON COLUMN "SYS_MENU"."COMPONENT" IS '组件路径';
COMMENT ON COLUMN "SYS_MENU"."PERMS" IS '权限标识';
COMMENT ON COLUMN "SYS_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "SYS_MENU"."SORT" IS '排序';
COMMENT ON COLUMN "SYS_MENU"."VISIBLE" IS '显示状态 0-隐藏 1-显示';
COMMENT ON COLUMN "SYS_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_MENU"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE OR REPLACE TRIGGER "TRG_SYS_MENU_UPDATE_TIME"
BEFORE UPDATE ON "SYS_MENU"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 用户角色关联表
-- ----------------------------
DROP TABLE IF EXISTS "SYS_USER_ROLE";
CREATE TABLE "SYS_USER_ROLE" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "USER_ID" BIGINT NOT NULL,
  "ROLE_ID" BIGINT NOT NULL,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID")
);
COMMENT ON TABLE "SYS_USER_ROLE" IS '用户角色关联表';
COMMENT ON COLUMN "SYS_USER_ROLE"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_USER_ROLE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYS_USER_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_USER_ROLE"."CREATE_TIME" IS '创建时间';

CREATE INDEX "IDX_SYS_USER_ROLE_USER_ID" ON "SYS_USER_ROLE" ("USER_ID");
CREATE INDEX "IDX_SYS_USER_ROLE_ROLE_ID" ON "SYS_USER_ROLE" ("ROLE_ID");

-- ----------------------------
-- 角色菜单关联表
-- ----------------------------
DROP TABLE IF EXISTS "SYS_ROLE_MENU";
CREATE TABLE "SYS_ROLE_MENU" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "ROLE_ID" BIGINT NOT NULL,
  "MENU_ID" BIGINT NOT NULL,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID")
);
COMMENT ON TABLE "SYS_ROLE_MENU" IS '角色菜单关联表';
COMMENT ON COLUMN "SYS_ROLE_MENU"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "SYS_ROLE_MENU"."CREATE_TIME" IS '创建时间';

CREATE INDEX "IDX_SYS_ROLE_MENU_ROLE_ID" ON "SYS_ROLE_MENU" ("ROLE_ID");
CREATE INDEX "IDX_SYS_ROLE_MENU_MENU_ID" ON "SYS_ROLE_MENU" ("MENU_ID");

-- ----------------------------
-- 数据源配置表
-- ----------------------------
DROP TABLE IF EXISTS "DATA_SOURCE_CONFIG";
CREATE TABLE "DATA_SOURCE_CONFIG" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "NAME" VARCHAR(128) NOT NULL,
  "CODE" VARCHAR(64) NOT NULL,
  "SOURCE_TYPE" VARCHAR(32) NOT NULL,
  "HOST" VARCHAR(128),
  "PORT" INT,
  "DATABASE_NAME" VARCHAR(128),
  "USERNAME" VARCHAR(64),
  "PASSWORD" VARCHAR(255),
  "JDBC_URL" VARCHAR(512),
  "DRIVER_CLASS" VARCHAR(255),
  "API_URL" VARCHAR(512),
  "API_METHOD" VARCHAR(16),
  "API_HEADERS" CLOB,
  "REMARK" VARCHAR(512),
  "STATUS" SMALLINT NOT NULL DEFAULT 1,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UK_DATA_SOURCE_CONFIG_CODE" UNIQUE ("CODE")
);
COMMENT ON TABLE "DATA_SOURCE_CONFIG" IS '数据源配置表';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."ID" IS '主键ID';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."NAME" IS '数据源名称';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."CODE" IS '数据源编码';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."SOURCE_TYPE" IS '数据源类型 MYSQL/ORACLE/POSTGRESQL/SQLSERVER/DM/API';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."HOST" IS '主机地址';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."PORT" IS '端口';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."DATABASE_NAME" IS '数据库名称';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."USERNAME" IS '用户名';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."PASSWORD" IS '密码';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."JDBC_URL" IS 'JDBC连接URL';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."DRIVER_CLASS" IS '驱动类名';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."API_URL" IS 'API地址';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."API_METHOD" IS 'API请求方法 GET/POST';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."API_HEADERS" IS 'API请求头(JSON)';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."STATUS" IS '状态 0-禁用 1-启用';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DATA_SOURCE_CONFIG"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE OR REPLACE TRIGGER "TRG_DATA_SOURCE_CONFIG_UPDATE"
BEFORE UPDATE ON "DATA_SOURCE_CONFIG"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 数据集表
-- ----------------------------
DROP TABLE IF EXISTS "DATA_SET";
CREATE TABLE "DATA_SET" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "NAME" VARCHAR(128) NOT NULL,
  "CODE" VARCHAR(64) NOT NULL,
  "DATA_SOURCE_ID" BIGINT NOT NULL,
  "SQL_TEXT" CLOB,
  "PARAMS" CLOB,
  "FIELDS" CLOB,
  "REMARK" VARCHAR(512),
  "STATUS" SMALLINT NOT NULL DEFAULT 1,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UK_DATA_SET_CODE" UNIQUE ("CODE")
);
COMMENT ON TABLE "DATA_SET" IS '数据集表';
COMMENT ON COLUMN "DATA_SET"."ID" IS '主键ID';
COMMENT ON COLUMN "DATA_SET"."NAME" IS '数据集名称';
COMMENT ON COLUMN "DATA_SET"."CODE" IS '数据集编码';
COMMENT ON COLUMN "DATA_SET"."DATA_SOURCE_ID" IS '数据源ID';
COMMENT ON COLUMN "DATA_SET"."SQL_TEXT" IS 'SQL语句';
COMMENT ON COLUMN "DATA_SET"."PARAMS" IS '参数定义(JSON)';
COMMENT ON COLUMN "DATA_SET"."FIELDS" IS '字段定义(JSON)';
COMMENT ON COLUMN "DATA_SET"."REMARK" IS '备注';
COMMENT ON COLUMN "DATA_SET"."STATUS" IS '状态 0-禁用 1-启用';
COMMENT ON COLUMN "DATA_SET"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DATA_SET"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DATA_SET"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DATA_SET"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DATA_SET"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE INDEX "IDX_DATA_SET_SOURCE_ID" ON "DATA_SET" ("DATA_SOURCE_ID");

CREATE OR REPLACE TRIGGER "TRG_DATA_SET_UPDATE_TIME"
BEFORE UPDATE ON "DATA_SET"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 报表模板表
-- ----------------------------
DROP TABLE IF EXISTS "REPORT_TEMPLATE";
CREATE TABLE "REPORT_TEMPLATE" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "NAME" VARCHAR(128) NOT NULL,
  "CODE" VARCHAR(64) NOT NULL,
  "TYPE" VARCHAR(32) NOT NULL,
  "TEMPLATE_JSON" CLOB,
  "THUMBNAIL" VARCHAR(512),
  "DESCRIPTION" VARCHAR(512),
  "PARAMS" CLOB,
  "DATA_SETS" CLOB,
  "STATUS" VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  "VERSION" INT NOT NULL DEFAULT 1,
  "VIEW_COUNT" BIGINT NOT NULL DEFAULT 0,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID"),
  CONSTRAINT "UK_REPORT_TEMPLATE_CODE" UNIQUE ("CODE")
);
COMMENT ON TABLE "REPORT_TEMPLATE" IS '报表模板表';
COMMENT ON COLUMN "REPORT_TEMPLATE"."ID" IS '主键ID';
COMMENT ON COLUMN "REPORT_TEMPLATE"."NAME" IS '报表名称';
COMMENT ON COLUMN "REPORT_TEMPLATE"."CODE" IS '报表编码';
COMMENT ON COLUMN "REPORT_TEMPLATE"."TYPE" IS '报表类型';
COMMENT ON COLUMN "REPORT_TEMPLATE"."TEMPLATE_JSON" IS '报表模板JSON';
COMMENT ON COLUMN "REPORT_TEMPLATE"."THUMBNAIL" IS '缩略图';
COMMENT ON COLUMN "REPORT_TEMPLATE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "REPORT_TEMPLATE"."PARAMS" IS '参数定义(JSON)';
COMMENT ON COLUMN "REPORT_TEMPLATE"."DATA_SETS" IS '数据集配置(JSON)';
COMMENT ON COLUMN "REPORT_TEMPLATE"."STATUS" IS '状态 DRAFT-草稿 PUBLISHED-已发布';
COMMENT ON COLUMN "REPORT_TEMPLATE"."VERSION" IS '版本号';
COMMENT ON COLUMN "REPORT_TEMPLATE"."VIEW_COUNT" IS '浏览次数';
COMMENT ON COLUMN "REPORT_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REPORT_TEMPLATE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "REPORT_TEMPLATE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "REPORT_TEMPLATE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "REPORT_TEMPLATE"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE OR REPLACE TRIGGER "TRG_REPORT_TEMPLATE_UPDATE"
BEFORE UPDATE ON "REPORT_TEMPLATE"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 报表调度表
-- ----------------------------
DROP TABLE IF EXISTS "REPORT_SCHEDULE";
CREATE TABLE "REPORT_SCHEDULE" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "REPORT_ID" BIGINT NOT NULL,
  "CRON_EXPRESSION" VARCHAR(128) NOT NULL,
  "PARAMS" CLOB,
  "OUTPUT_TYPE" VARCHAR(32) NOT NULL,
  "EMAIL_LIST" VARCHAR(1024),
  "STATUS" SMALLINT NOT NULL DEFAULT 1,
  "LAST_EXECUTE_TIME" TIMESTAMP,
  "NEXT_EXECUTE_TIME" TIMESTAMP,
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATE_BY" BIGINT,
  "UPDATE_BY" BIGINT,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID")
);
COMMENT ON TABLE "REPORT_SCHEDULE" IS '报表调度表';
COMMENT ON COLUMN "REPORT_SCHEDULE"."ID" IS '主键ID';
COMMENT ON COLUMN "REPORT_SCHEDULE"."REPORT_ID" IS '报表ID';
COMMENT ON COLUMN "REPORT_SCHEDULE"."CRON_EXPRESSION" IS 'Cron表达式';
COMMENT ON COLUMN "REPORT_SCHEDULE"."PARAMS" IS '执行参数(JSON)';
COMMENT ON COLUMN "REPORT_SCHEDULE"."OUTPUT_TYPE" IS '输出类型 PDF/EXCEL/IMAGE/EMAIL';
COMMENT ON COLUMN "REPORT_SCHEDULE"."EMAIL_LIST" IS '邮件收件人列表(逗号分隔)';
COMMENT ON COLUMN "REPORT_SCHEDULE"."STATUS" IS '状态 0-停用 1-启用';
COMMENT ON COLUMN "REPORT_SCHEDULE"."LAST_EXECUTE_TIME" IS '上次执行时间';
COMMENT ON COLUMN "REPORT_SCHEDULE"."NEXT_EXECUTE_TIME" IS '下次执行时间';
COMMENT ON COLUMN "REPORT_SCHEDULE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REPORT_SCHEDULE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "REPORT_SCHEDULE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "REPORT_SCHEDULE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "REPORT_SCHEDULE"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE INDEX "IDX_REPORT_SCHEDULE_REPORT_ID" ON "REPORT_SCHEDULE" ("REPORT_ID");

CREATE OR REPLACE TRIGGER "TRG_REPORT_SCHEDULE_UPDATE"
BEFORE UPDATE ON "REPORT_SCHEDULE"
FOR EACH ROW
BEGIN
  :NEW."UPDATE_TIME" := CURRENT_TIMESTAMP;
END;
/

-- ----------------------------
-- 报表执行日志表
-- ----------------------------
DROP TABLE IF EXISTS "REPORT_LOG";
CREATE TABLE "REPORT_LOG" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "REPORT_ID" BIGINT NOT NULL,
  "EXECUTE_TYPE" VARCHAR(32) NOT NULL,
  "PARAMS" CLOB,
  "STATUS" VARCHAR(32) NOT NULL,
  "COST_TIME" BIGINT,
  "ERROR_MSG" CLOB,
  "OUTPUT_PATH" VARCHAR(512),
  "CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DELETED" SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("ID")
);
COMMENT ON TABLE "REPORT_LOG" IS '报表执行日志表';
COMMENT ON COLUMN "REPORT_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "REPORT_LOG"."REPORT_ID" IS '报表ID';
COMMENT ON COLUMN "REPORT_LOG"."EXECUTE_TYPE" IS '执行类型 MANUAL-手动 SCHEDULE-定时';
COMMENT ON COLUMN "REPORT_LOG"."PARAMS" IS '执行参数(JSON)';
COMMENT ON COLUMN "REPORT_LOG"."STATUS" IS '执行状态 SUCCESS-成功 FAIL-失败';
COMMENT ON COLUMN "REPORT_LOG"."COST_TIME" IS '耗时(毫秒)';
COMMENT ON COLUMN "REPORT_LOG"."ERROR_MSG" IS '错误信息';
COMMENT ON COLUMN "REPORT_LOG"."OUTPUT_PATH" IS '输出文件路径';
COMMENT ON COLUMN "REPORT_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REPORT_LOG"."DELETED" IS '逻辑删除 0-未删除 1-已删除';

CREATE INDEX "IDX_REPORT_LOG_REPORT_ID" ON "REPORT_LOG" ("REPORT_ID");
